### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by joekinley** [underscorediscovery/luxe#270] opened 2015-05-09 20:01 UTC
On Linux, when running "flow run linux", 9 out of 10 times I get this error:

```
flow / 1.0.0-alpha.1
flow / target is linux ( arch 64 )
flow / haxe version 3.1.3

flow / build - aymuraykilla 0.0.1 for linux
flow / no icon convert just yet for linux
flow / build - running haxe ...
/usr/lib/haxe/std/neko/_std/Sys.hx:25: characters 10-28 : Broken pipe
/usr/lib/haxe/lib/haxelib_client/3,2,0-rc,3/src/tools/haxelib/Main.hx:1504: characters 2-21 : Called from
/usr/lib/haxe/lib/haxelib_client/3,2,0-rc,3/src/tools/haxelib/Main.hx:377: characters 5-25 : Called from
/usr/lib/haxe/lib/haxelib_client/3,2,0-rc,3/src/tools/haxelib/Main.hx:1508: characters 2-22 : Called from
--macro:1: character 0 : Called from
Aborted
```

Rerunning it often enough it doesn't come anymore. So just appears sometimes (most times unfortunately).

Running on haxe 3.1.3 with latest updates at the current moment.

**Comment by anissen** [comment] 2015-05-09 20:23
This is more of a `flow`-related issue. In fact, it's a duplicate of https://github.com/underscorediscovery/flow/issues/29.

**Comment by underscorediscovery** [comment] 2015-05-09 20:23
https://github.com/underscorediscovery/flow/issues/29

**Closed** 2015-05-09 20:23 UTC
